version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data source from gz
    tables:
      - name: product
        identifier: raw_gz_product
        description: product data with one row for price of each product_id
        columns:
          - name: products_id
            description: primary key of the table
        tests:
          - unique:
              column_name: products_id 
      - name: sales
        identifier: raw_gz_sales
        description: daily sales data
        columns:
          - name: orders_product
            description: primary key of sales table
        tests:
          - unique:
              column_name: "(order_id || ' - ' || products_id)"
      - name: ship
        identifier: raw_gz_ship
        description: daily shipping data
